name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install xvfb
      run: sudo apt-get install -y xvfb

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Choose browser for Playwright tests
      id: browser-choice
      run: echo "Selected browser: ${{ github.event.inputs.browser || 'chromium' }}"  
      # Default to chromium if not provided
      env:
        browser: "${{ github.event.inputs.browser || 'chromium' }}"  
        # You can specify the browser through GitHub actions inputs

    - name: Run Playwright tests
      run: |
        if [[ "${{ github.event.inputs.browser || 'chromium' }}" == "firefox" ]]; then
          xvfb-run npx playwright test --project=firefox
        elif [[ "${{ github.event.inputs.browser || 'chromium' }}" == "webkit" ]]; then
          xvfb-run npx playwright test --project=webkit
        else
          xvfb-run npx playwright test --project=chromium
        fi

    - name: Run Playwright tests
      run: xvfb-run npx playwright test  # Run the tests with xvfb

    - uses: actions/upload-artifact@v4
      if: ${{!cancelled()}}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
